/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const GET_MOVIES_LIST = 'GET_MOVIES_LIST';
export const GET_MOVIES_LIST_SUCCESS = 'GET_MOVIES_LIST_SUCCESS';
export const GET_MOVIES_LIST_FAIL = 'GET_MOVIES_LIST_FAIL';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';

export const GET_GENRES_LIST_SUCCESS = 'GET_GENRES_LIST_SUCCESS';
export const GET_GENRES_LIST_FAIL = 'GET_GENRES_LIST_FAIL';

export const ERROR_CLEAR = 'ERROR_CLEAR';
export const ERROR_SET = 'ERROR_SET';

export const CLEAR_MOVIE = 'CLEAR_MOVIE';
export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL';

export const GET_SIMILAR_SUCCESS = 'GET_SIMILAR_SUCCESS';
export const GET_SIMILAR_FAIL = 'GET_SIMILAR_FAIL';
